---
- name: Run packer
  vars:
    _log_suffix: >-
      {{
        (
          ('-' + (_pbi_packer_build_name | regex_replace('[^a-zA-Z\d-]', '')))
          if _pbi_packer_build_name | length > 0 else ''
        ) + '.log'
      }}
  block:
    - name: Run packer init
      pbtn.common.script:
        cmd: >-
          {{ _pbi_packer_binary }}
          init
          {{
            pbi_packer_force_init | ternary('-force', '')
          }}
          {{
            _pbi_packer_template_path_sanitized
          }}
        log_path: >-
          {{
            (ansible_user_dir, "logs", "packer-init" + _log_suffix) | path_join
          }}
        log_combine: true
        log_timestamp: true
        chdir: "{{ _pbi_packer_base_run_dir }}"
      register: _pbi_packer_init_cmd_out
      changed_when: "_pbi_packer_init_cmd_out.stdout | length != 0"

    - name: Run packer build
      pbtn.common.script:
        cmd: >-
          {{ _pbi_packer_binary }}
          build
          -color=false
          {{
            pbi_packer_debug | ternary('-debug', '')
          }}
          {{
            (
              ['-var-file '] |
              product(_pbi_packer_variable_files_sanitized) | flatten | join(' ')
            ) if _pbi_packer_variable_files_sanitized | length > 0 else ''
          }}
          {{
            _pbi_packer_template_path_sanitized
          }}
        log_path: >-
          {{
            (ansible_user_dir, "logs", "packer-build" + _log_suffix) | path_join
          }}
        log_combine: true
        log_timestamp: true
        chdir: "{{ _pbi_packer_base_run_dir }}"
      register: _pbi_packer_build_cmd_out
      changed_when: true
